# Generated by Django 5.1.3 on 2026-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_id", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
