# Generated by Django 5.1.3 on 2026-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("quiz1", models.FloatField(default=0.0)),
                ("quiz2", models.FloatField(default=0.0)),
                ("quiz3", models.FloatField(default=0.0)),
                ("quiz4", models.FloatField(default=0.0)),
                ("assign1", models.FloatField(default=0.0)),
                ("assign2", models.FloatField(default=0.0)),
                ("assign3", models.FloatField(default=0.0)),
                ("assign4", models.FloatField(default=0.0)),
                ("midterm", models.FloatField(default=0.0)),
                ("final", models.FloatField(default=0.0)),
                ("total", models.FloatField(default=0.0)),
                ("status", models.CharField(default="Fail", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["student_name"],
            },
        ),
    ]
