# Generated by Django 5.1.3 on 2026-10-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CLO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                ("domain", models.CharField(blank=True, max_length=50, null=True)),
                ("bt_level", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "course",
                    models.CharField(
                        blank=True,
                        help_text="Optional course reference. Replace with a ForeignKey to your Course model when available.",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("assessment_type", models.CharField(max_length=50)),
                (
                    "source_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CLOMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("auto_mapped", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clo_mapper.clo"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="clo_mapper.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("question", "auto_mapped")},
            },
        ),
    ]
