# Generated by Django 5.1.3 on 2026-10-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(blank=True, max_length=64)),
                ("course_name", models.CharField(blank=True, max_length=255)),
                ("course_instructor", models.CharField(blank=True, max_length=255)),
                ("semester", models.CharField(blank=True, max_length=64)),
                (
                    "sections",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Sections (e.g. BS(SE)-1A)",
                    ),
                ),
                (
                    "total_credits",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        verbose_name="Total Credits (e.g. 3 (2,1))",
                    ),
                ),
                (
                    "academic_term",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Academic Term (e.g. Fall 2024)",
                    ),
                ),
                (
                    "catalog_description",
                    models.TextField(
                        blank=True, verbose_name="Current Catalog Description"
                    ),
                ),
                (
                    "modifications_made",
                    models.TextField(
                        blank=True,
                        default="None",
                        verbose_name="Modifications Made to Course",
                    ),
                ),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("clo1_avg", models.FloatField(default=0.0)),
                ("clo2_avg", models.FloatField(default=0.0)),
                ("clo3_avg", models.FloatField(default=0.0)),
                ("clo4_avg", models.FloatField(default=0.0)),
                ("epan_avg", models.FloatField(default=0.0)),
                ("achievement_level", models.CharField(blank=True, max_length=32)),
                ("grade_distribution", models.JSONField(blank=True, default=dict)),
                ("assessment_averages", models.JSONField(blank=True, default=dict)),
                ("student_feedback", models.TextField(blank=True)),
                ("reflection", models.TextField(blank=True)),
                ("proposed_improvements", models.TextField(blank=True)),
                ("status", models.CharField(default="uploaded", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademicReportStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                ("quiz1", models.FloatField(default=0.0)),
                ("quiz2", models.FloatField(default=0.0)),
                ("quiz3", models.FloatField(default=0.0)),
                ("quiz4", models.FloatField(default=0.0)),
                ("assign1", models.FloatField(default=0.0)),
                ("assign2", models.FloatField(default=0.0)),
                ("assign3", models.FloatField(default=0.0)),
                ("assign4", models.FloatField(default=0.0)),
                ("mid_q1", models.FloatField(default=0.0)),
                ("mid_q2", models.FloatField(default=0.0)),
                ("mid_q3", models.FloatField(default=0.0)),
                ("mid_q4", models.FloatField(default=0.0)),
                ("final_q1", models.FloatField(default=0.0)),
                ("final_q2", models.FloatField(default=0.0)),
                ("final_q3", models.FloatField(default=0.0)),
                ("final_q4", models.FloatField(default=0.0)),
                ("final_viva", models.FloatField(default=0.0)),
                ("clo1_score", models.FloatField(default=0.0)),
                ("clo2_score", models.FloatField(default=0.0)),
                ("clo3_score", models.FloatField(default=0.0)),
                ("clo4_score", models.FloatField(default=0.0)),
                ("total_score", models.FloatField(default=0.0)),
                ("grade_letter", models.CharField(blank=True, max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="academic_report.academicreportrun",
                    ),
                ),
            ],
            options={
                "ordering": ["student_name"],
            },
        ),
    ]
