# Generated by Django 5.1.3 on 2026-10-05 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacultyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("profile_image", models.URLField(blank=True)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DriveFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_file_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("folder_id", models.CharField(blank=True, max_length=255)),
                ("web_view_link", models.URLField(blank=True)),
                ("web_content_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_files",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("section", models.CharField(blank=True, max_length=255)),
                ("description_heading", models.CharField(blank=True, max_length=255)),
                ("enrollment_code", models.CharField(blank=True, max_length=64)),
                ("alternate_link", models.URLField(blank=True)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_courses",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "course_id")},
            },
        ),
        migrations.CreateModel(
            name="GoogleServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_token",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MidtermEvaluationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("source_file_path", models.TextField(blank=True)),
                ("source_file_type", models.CharField(default=".xlsx", max_length=16)),
                ("source_sheet_name", models.CharField(blank=True, max_length=128)),
                ("max_marks", models.FloatField(default=30.0)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("pass_count", models.PositiveIntegerField(default=0)),
                ("fail_count", models.PositiveIntegerField(default=0)),
                ("pass_percentage", models.FloatField(default=0.0)),
                ("highest_marks", models.FloatField(blank=True, null=True)),
                ("highest_student_name", models.CharField(blank=True, max_length=255)),
                ("lowest_marks", models.FloatField(blank=True, null=True)),
                ("lowest_student_name", models.CharField(blank=True, max_length=255)),
                ("average_marks", models.FloatField(blank=True, null=True)),
                ("median_marks", models.FloatField(blank=True, null=True)),
                ("grade_distribution", models.JSONField(blank=True, default=dict)),
                (
                    "performance_distribution",
                    models.JSONField(blank=True, default=dict),
                ),
                ("status", models.CharField(default="uploaded", max_length=32)),
                ("error_message", models.TextField(blank=True)),
                ("report_file_name", models.CharField(blank=True, max_length=255)),
                ("report_generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="midterm_evaluation_runs",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MidtermEvaluationStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(default=0)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                ("student_name", models.CharField(blank=True, max_length=255)),
                ("midterm_marks", models.FloatField(blank=True, null=True)),
                ("grade_letter", models.CharField(blank=True, max_length=4)),
                ("gpa", models.FloatField(blank=True, null=True)),
                ("performance_band", models.CharField(blank=True, max_length=32)),
                ("risk_status", models.CharField(blank=True, max_length=64)),
                ("is_pass", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="auth_app.midtermevaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["registration_no", "student_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentOutreachEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatch_batch_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("recipient_type", models.CharField(default="student", max_length=32)),
                ("student_name", models.CharField(blank=True, max_length=255)),
                ("registration_no", models.CharField(blank=True, max_length=64)),
                ("email_address", models.EmailField(max_length=254)),
                ("midterm_marks", models.FloatField(blank=True, null=True)),
                ("grade_letter", models.CharField(blank=True, max_length=4)),
                ("risk_level", models.CharField(blank=True, max_length=64)),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("status", models.CharField(default="failed", max_length=16)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_email_logs",
                        to="auth_app.midtermevaluationrun",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_email_logs",
                        to="auth_app.midtermevaluationstudent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_outreach_email_logs",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ZabdeskMarkEntryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_type", models.CharField(max_length=64)),
                ("marks_type_label", models.CharField(max_length=64)),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("failures", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(default="completed", max_length=32)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zabdesk_mark_entry_runs",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomCoursework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_google_id", models.CharField(db_index=True, max_length=128)),
                ("coursework_id", models.CharField(db_index=True, max_length=128)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("alternate_link", models.URLField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("due_time", models.CharField(blank=True, max_length=16)),
                ("max_points", models.FloatField(blank=True, null=True)),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coursework",
                        to="auth_app.classroomcourse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_coursework",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("course_google_id", "coursework_id", "user")},
            },
        ),
    ]
