# Generated by Django 5.1.3 on 2026-10-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="e.g. 'Course Outline', 'Quiz 1 Entries'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "deadline_date",
                    models.DateTimeField(
                        help_text="Deadline date/time in Asia/Karachi timezone"
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Week number for reference (e.g. Week 0, Week 3)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional context for the reminder email",
                    ),
                ),
                (
                    "reminder_offsets",
                    models.JSONField(
                        default=list,
                        help_text="List of days before deadline to send reminder (e.g. [7, 3, 1])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to pause reminders for this deadline",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Deadline",
                "verbose_name_plural": "Deadlines",
                "ordering": ["deadline_date"],
                "indexes": [
                    models.Index(
                        fields=["deadline_date", "is_active"],
                        name="auto_remind_deadlin_9f4b5c_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="auto_remind_is_acti_b554b1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReminderPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_reminders",
                    models.BooleanField(
                        default=True, help_text="Master toggle for all reminders"
                    ),
                ),
                (
                    "email_override",
                    models.EmailField(
                        blank=True,
                        help_text="Optional: send reminders to this email instead of faculty email",
                        max_length=254,
                    ),
                ),
                (
                    "recipient_emails",
                    models.JSONField(
                        default=list,
                        help_text="List of recipient emails (overrides single email_override if set)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_preference",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Preference",
                "verbose_name_plural": "Reminder Preferences",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_date", models.DateField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        help_text="External identifier to prevent duplicates (e.g., coursework ID or deadline key)",
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="auth_app.classroomcourse",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="auth_app.facultyuser",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="auto_reminder.alertstatus",
                    ),
                ),
                (
                    "alert_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="auto_reminder.alerttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trigger_date", "status"],
                        name="auto_remind_trigger_313754_idx",
                    ),
                    models.Index(
                        fields=["faculty", "status"],
                        name="auto_remind_faculty_69e3d5_idx",
                    ),
                ],
                "unique_together": {("faculty", "course", "alert_type", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="AssignmentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(
                        help_text="Google Classroom course ID", max_length=128
                    ),
                ),
                (
                    "assignment_id",
                    models.CharField(
                        help_text="Google Classroom coursework ID", max_length=128
                    ),
                ),
                (
                    "assignment_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Assignment sequence number", null=True
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="Entry/deadline date for the assignment",
                        null=True,
                    ),
                ),
                (
                    "quiz_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quiz sequence number for entry deadlines",
                        null=True,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        blank=True,
                        help_text="Mid term event name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True,
                        help_text="Mid term event date (start for ranges)",
                        null=True,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("created", "Assignment created"),
                            ("deadline", "Deadline approaching"),
                            ("summary", "Submission summary"),
                            ("entry_deadline", "Assignment entry deadline"),
                            ("quiz_entry_deadline", "Quiz entry deadline"),
                            ("mid_term_event", "Mid term event"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "alert_stage",
                    models.CharField(
                        choices=[
                            ("three_days", "3 days before"),
                            ("two_days", "2 days before"),
                            ("one_day", "1 day before"),
                            ("today", "Deadline day"),
                            ("overdue", "Overdue"),
                            ("single", "Single/legacy"),
                        ],
                        default="single",
                        help_text="Multi-stage reminder bucket (3d/2d/1d/today/overdue)",
                        max_length=32,
                    ),
                ),
                (
                    "alert_target",
                    models.CharField(
                        choices=[("faculty", "Faculty"), ("student", "Student")],
                        default="faculty",
                        help_text="Who should see this alert",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent")],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Marked done by faculty to stop future alerts",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Last known submission summary",
                    ),
                ),
                (
                    "calendar_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Calendar event id to prevent duplicate creations",
                        max_length=256,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        default="ok",
                        help_text="Last sync status for Calendar/Email actions",
                        max_length=32,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last sync error message (for support/debug)",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_assignment_alerts",
                        to="auth_app.facultyuser",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_alerts",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["faculty", "status"],
                        name="auto_remind_faculty_d9007f_idx",
                    ),
                    models.Index(
                        fields=["course_id", "assignment_id"],
                        name="auto_remind_course__61adc9_idx",
                    ),
                    models.Index(
                        fields=["assignment_number", "deadline_date"],
                        name="auto_remind_assignm_118fa4_idx",
                    ),
                    models.Index(
                        fields=["quiz_number", "deadline_date"],
                        name="auto_remind_quiz_nu_c2d14a_idx",
                    ),
                    models.Index(
                        fields=["event_date", "alert_type"],
                        name="auto_remind_event_d_ec0d7b_idx",
                    ),
                    models.Index(
                        fields=["alert_stage", "alert_type"],
                        name="auto_remind_alert_s_057593_idx",
                    ),
                    models.Index(
                        fields=["is_completed", "deadline_date"],
                        name="auto_remind_is_comp_b21bdc_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "faculty",
                        "course_id",
                        "assignment_id",
                        "alert_type",
                        "alert_stage",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset_days",
                    models.IntegerField(
                        help_text="Which reminder trigger: 7, 3, or 1 days before"
                    ),
                ),
                (
                    "email_recipient",
                    models.EmailField(
                        help_text="Email address that received the reminder",
                        max_length=254,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the reminder was sent (UTC, stored timezone-aware)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Successfully sent"),
                            ("failed", "Failed to send"),
                            ("skipped", "Skipped (user disabled)"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if status is 'failed'"
                    ),
                ),
                (
                    "deadline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="auto_reminder.deadline",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="auth_app.facultyuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Log",
                "verbose_name_plural": "Reminder Logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["faculty", "deadline", "offset_days"],
                        name="auto_remind_faculty_ec66a7_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="auto_remind_sent_at_fbee6a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="auto_remind_status_e4d857_idx"
                    ),
                ],
                "unique_together": {("faculty", "deadline", "offset_days")},
            },
        ),
    ]
