from django.urls import path

from . import views

app_name = "auth_app"

urlpatterns = [
    path("", views.home_redirect, name="home"),
    path("login/", views.login_page, name="login"),
    path("unauthorized/", views.unauthorized_page, name="unauthorized"),
    path("dashboard/", views.dashboard_page, name="dashboard"),
    path("curriculum/", views.curriculum_page, name="curriculum"),
    path("google-services/", views.google_services_page, name="google_services"),
    path("google/connect/", views.google_services_connect, name="google_services_connect"),
    path("google/callback/", views.google_services_callback, name="google_services_callback"),
    path("google/status/", views.google_services_status, name="google_services_status"),
    path("google/disconnect/", views.google_services_disconnect, name="google_services_disconnect"),
    path("google/drive/upload/", views.google_drive_upload, name="google_drive_upload"),
    path("google/drive/files/", views.google_drive_files, name="google_drive_files"),
    path("google/drive/files/<str:file_id>/", views.google_drive_delete, name="google_drive_delete"),
    path("google/classroom/create-course/", views.google_classroom_create_course, name="google_classroom_create_course"),
    path("google/classroom/courses/", views.google_classroom_courses, name="google_classroom_courses"),
    path("google/classroom/coursework/", views.google_classroom_coursework, name="google_classroom_coursework"),
    path("google/classroom/material/upload/", views.google_classroom_material_upload, name="google_classroom_material_upload"),
    path("google/classroom/submissions/", views.google_classroom_submissions, name="google_classroom_submissions"),
    path("auto-reminder/", views.auto_reminder_page, name="auto_reminder"),
    path("auto-alert/", views.auto_alert_page, name="auto_alert_legacy"),
    path("zabdesk-marks-bridge/", views.zabdesk_marks_bridge_page, name="zabdesk_marks_bridge"),
    path("midterm-academic-evaluator/", views.midterm_academic_evaluator_page, name="midterm_academic_evaluator"),
    path("student-outreach-assistant/", views.student_outreach_assistant_page, name="student_outreach_assistant"),
    path("zabdesk-auto-login/", views.zabdesk_auto_login, name="zabdesk_auto_login"),
    path("zabdesk-upload-excel/", views.zabdesk_upload_excel, name="zabdesk_upload_excel"),
    path("zabdesk-extract-excel/", views.zabdesk_extract_excel_data, name="zabdesk_extract_excel_data"),
    path("zabdesk-enter-marks/", views.zabdesk_enter_marks_in_recap_sheet, name="zabdesk_enter_marks_in_recap_sheet"),
    path("midterm-upload-excel/", views.midterm_upload_excel, name="midterm_upload_excel"),
    path("midterm-extract-data/", views.midterm_extract_data, name="midterm_extract_data"),
    path("midterm-evaluate-data/", views.midterm_evaluate_data, name="midterm_evaluate_data"),
    path("midterm-generate-report/", views.midterm_generate_report, name="midterm_generate_report"),
    path("student-outreach-at-risk/", views.student_outreach_at_risk_students, name="student_outreach_at_risk_students"),
    path("student-outreach-preview-email/", views.student_outreach_preview_email, name="student_outreach_preview_email"),
    path("student-outreach-send-single/", views.student_outreach_send_single, name="student_outreach_send_single"),
    path("student-outreach-send-faculty-summary/", views.student_outreach_send_faculty_summary, name="student_outreach_send_faculty_summary"),
    path("student-outreach-email-history/", views.student_outreach_email_history, name="student_outreach_email_history"),
    path("student-outreach-resend-failed/", views.student_outreach_resend_failed, name="student_outreach_resend_failed"),
    path("open-browser/", views.open_portal_browser, name="open_portal_browser"),
    path("process-curriculum/", views.process_curriculum_automation, name="process_curriculum_automation"),
    path("upload-curriculum/", views.upload_curriculum, name="upload_curriculum"),
    path("run-curriculum-automation/", views.run_curriculum_automation, name="run_curriculum_automation"),
    path("google/", views.google_login, name="google-login"),
    path("callback/", views.google_callback, name="google-callback"),
    path("logout/", views.logout_view, name="logout"),
    path("user/", views.current_user, name="current-user"),
    # ── Attendance Exemption Module ──────────────────────────────────────────
    path("attendance-exemption/", views.attendance_exemption_page, name="attendance_exemption"),
    path("attendance-exemption/fetch/", views.attendance_fetch, name="attendance_fetch"),
    path("attendance-exemption/process/", views.attendance_process_exemption, name="attendance_process_exemption"),
    path("attendance-exemption/close-portal/", views.attendance_close_portal, name="attendance_close_portal"),
]
